const fleetData=window.dashboardData||[];
fleetData.forEach(row=>{if(row.Serv==='Ser')row.Serv='Svc';if(row.Serv==='Unser')row.Serv='Unsvc'});
const $=id=>document.getElementById(id);
const fields=[['Drone Name','text'],['Type','select'],['Form Factor','select'],['OEM','select'],['Range','select'],['Weight (KG)','number'],['Endurance (min)','number'],['C2 Link Frequency','select'],['Proc Fund','select'],['Serv','select'],['Cost (in Thousands)','number'],['Image Front','file'],['Image Back','file'],['Image Top','file'],['Image Bottom','file'],['Unit','select'],['Brigade','select'],['Division','select'],['Corps','select'],['Command','select']];
const fixed={Range:['< 5 km','5-10 km','10-30 km','31-100 km','> 100 km'],'C2 Link Frequency':['1.4 GHz','2.4 GHz','5.8 GHz','900 MHz'],'Proc Fund':['ATG','Regtl','Unit','Central'],'Anti Ew':['Nil'],Serv:['Ser','Unser']};
const options=field=>[...new Set([...(fixed[field]||[]),...fleetData.map(row=>row[field]).filter(Boolean)])].sort();
const fragment=(value,length)=>String(value||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase().slice(0,length).padEnd(length,'X');
const nextSerial=()=>fleetData.reduce((max,row)=>Math.max(max,Number(row['Ser No'])||0),0)+1;
function makeDroneId(value){const base=[fragment(value.Command,2),fragment(value.Corps,2),fragment(value.Division,3),fragment(value.Brigade,4),fragment(value.Unit,4),fragment(value['Drone Name'],3),fragment(value.Type,3),String(value['Ser No']||1).padStart(2,'0')].join('-');const repeat=fleetData.filter(row=>row['Drone ID']===base||String(row['Drone ID']||'').startsWith(`${base}-`)).length;return repeat?`${base}-${String(repeat+1).padStart(2,'0')}`:base}
function countBy(field){return [...new Set(fleetData.map(row=>row[field]).filter(Boolean))].map(value=>[value,fleetData.filter(row=>row[field]===value).length])}
function renderOverview(){const total=fleetData.length,ready=fleetData.filter(row=>row.Serv==='Svc').length,units=new Set(fleetData.map(row=>row.Unit)).size,value=fleetData.reduce((sum,row)=>sum+Number(row['Cost (in Thousands)']||0),0),rate=total?ready/total*100:0;$('coverage-summary').textContent=`${total} records · ${units} units`;$('attention-count').textContent=total-ready;$('hero-attention').textContent=total-ready;$('total-holdings').textContent=total;$('active-fleet').textContent=ready;$('active-rate').textContent=`${rate.toFixed(1)}%`;$('hero-readiness').textContent=`${rate.toFixed(1)}%`;$('donut-readiness').textContent=`${rate.toFixed(1)}%`;$('unit-count').textContent=`${units} unit locations`;$('register-value').textContent=`₹${(value/10000).toFixed(1)} Cr`;$('largest-attention').textContent=`Unsvc · ${fleetData.filter(row=>row.Serv==='Unsvc').length} assets`}
function renderOverview(){const total=fleetData.length,ready=fleetData.filter(row=>row.Serv==='Svc').length,units=new Set(fleetData.map(row=>row.Unit)).size,value=fleetData.reduce((sum,row)=>sum+Number(row['Cost (in Thousands)']||0),0),rate=total?ready/total*100:0,ew=total?fleetData.filter(row=>row['Anti Ew']&&row['Anti Ew'].toLowerCase()!=='none').length/total*100:0;$('coverage-summary').textContent=`${total} records · ${units} units`;$('attention-count').textContent=total-ready;$('hero-attention').textContent=total-ready;$('total-holdings').textContent=total;$('active-fleet').textContent=ready;$('active-rate').textContent=`${rate.toFixed(1)}%`;$('hero-readiness').textContent=`${rate.toFixed(1)}%`;$('donut-readiness').textContent=`${rate.toFixed(1)}%`;$('register-value').textContent=`₹${(value/10000).toFixed(1)} Cr`;$('ew-resilience').textContent=`${ew.toFixed(1)}%`;$('largest-attention').textContent=`Unsvc · ${fleetData.filter(row=>row.Serv==='Unsvc').length} assets`}
function renderBars(target,data,total){$(target).innerHTML=data.map(([name,count])=>`<div class="bar-row"><span>${name}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,count/total*100)}%"></div></div><strong>${count}</strong></div>`).join('')}
function renderService(){const total=fleetData.length||1;$('service-legend').innerHTML=[['Serviceable','Svc'],['Unserviceable','Unsvc'],['Decommissioned','Decommissioned']].map(([label,key])=>{const count=fleetData.filter(row=>row.Serv===key).length;return `<div class="legend-row"><span>${label}</span><strong>${count} <small>${(count/total*100).toFixed(1)}%</small></strong></div>`}).join('')}
function renderGuidance(){$('guidance-list').innerHTML=countBy('Guidance').map(([name,count])=>`<div class="guidance-item"><span>${name}</span><strong>${count}</strong></div>`).join('')}
function renderProcFund(){renderBars('proc-fund-bars',countBy('Proc Fund'),fleetData.length)}
function renderEWProfiles(){const profiles=countBy('Anti Ew');renderBars('ew-profile-bars',profiles,fleetData.length)}
function renderUnits(filter='all'){const rows=fleetData.filter(row=>filter==='all'||row.Brigade===filter);const groups=[...new Set(rows.map(row=>`${row.Unit}|${row.Brigade}`))].map(key=>{const [unit,brigade]=key.split('|'),unitRows=rows.filter(row=>row.Unit===unit);return [unit,brigade,unitRows.length,unitRows.filter(row=>row.Serv==='Svc').length]});$('unit-table').innerHTML='<div class="table-head"><span>UNIT</span><span>BRIGADE</span><span>HOLDINGS</span><span>READY</span></div>'+groups.map(row=>`<div class="table-row"><strong>${row[0]}</strong><small>${row[1]}</small><span>${row[2]}</span><span class="ready">${row[3]}</span></div>`).join('')}
function filterValue(id){return $(id)?.value||'all'}
function renderFleet(query=''){const filters=[['Command','command-filter'],['Corps','corps-filter'],['Division','division-filter'],['Brigade','brigade-filter']];const rows=fleetData.filter(row=>Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase())&&filters.every(([field,id])=>filterValue(id)==='all'||row[field]===filterValue(id)));$('result-count').textContent=`Showing ${rows.length} record${rows.length===1?'':'s'}`;$('fleet-table').innerHTML='<div class="table-head"><span>DRONE ID</span><span>DRONE NAME</span><span>UNIT</span><span>TYPE</span><span>STATUS</span><span></span></div>'+rows.map(row=>`<div class="table-row"><strong>${row['Drone ID']}</strong><span>${row['Drone Name']}</span><small>${row.Unit}</small><span>${row.Type}</span><span class="status-badge ${row.Serv!=='Svc'?'warn':''}">${row.Serv}</span>${window.userRole==='admin'?`<button class="delete-button" data-delete-id="${row['Drone ID']}" title="Delete asset" aria-label="Delete asset">×</button>`:''}</div>`).join('');document.querySelectorAll('[data-delete-id]').forEach(button=>button.addEventListener('click',deleteAsset))}
function populateFilter(id,field){[...new Set(fleetData.map(row=>row[field]).filter(Boolean))].sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;$(id).appendChild(option)})}
async function deleteAsset(event){const droneId=event.currentTarget.dataset.deleteId;if(!window.confirm(`Delete ${droneId}?`))return;const response=await fetch(`/api/assets/${encodeURIComponent(droneId)}`,{method:'DELETE',headers:{'X-Role':window.userRole}});if(!response.ok){$('form-message').textContent='Delete failed: Admin role required.';return}const index=fleetData.findIndex(row=>row['Drone ID']===droneId);if(index>=0)fleetData.splice(index,1);renderOverview();renderEWProfiles();renderFleet($('fleet-search').value)}
function readForm(){const value={};new FormData($('asset-form')).forEach((entry,key)=>{if(!key.startsWith('Image'))value[key]=entry});for(const [field,type] of fields.filter(([,type])=>type==='select'))if(value[field]==='__new__')value[field]=document.querySelector(`[data-for="${field}"]`).value.trim();for(const kind of ['payload','guidance','anti-ew']){const rows=[...document.querySelectorAll(`#${kind}-rows .multi-row`)],names=rows.map(row=>{const select=row.querySelector('[data-multi]'),custom=row.querySelector(`[data-multi-new="${kind}"]`);return (select.value==='__new__'?custom.value:select.value).trim()}).filter(Boolean),key=kind==='anti-ew'?'Anti Ew':kind[0].toUpperCase()+kind.slice(1);value[key]=names.join('; ');if(kind==='payload'){value.Payload=names.join('; ');value['Payload Weight']=rows.map(row=>row.querySelector('[data-multi-weight]').value).join('; ');value['Payload Description']=rows.map(row=>row.querySelector('[data-multi-description]').value.trim()).join('; ')}}return value}
function addMultiRow(kind){const target=$(`${kind}-rows`),name=kind==='payload'?'Payload':kind==='guidance'?'Guidance':'Anti-EW',field=kind==='anti-ew'?'Anti Ew':name,row=document.createElement('div'),list=options(field).map(value=>`<option value="${value}">${value==='Nil'?'Nil - Not EW resilient':value}</option>`).join('');row.className=`multi-row ${kind}-row`;row.innerHTML=`<select data-multi="${kind}" required><option value="">Select ${name}</option>${list}<option value="__new__">+ Add new value...</option></select><input class="new-multi-option hidden" data-multi-new="${kind}" placeholder="Enter new ${name.toLowerCase()}">${kind==='payload'?'<input data-multi-weight type="number" min="0" step="any" placeholder="Weight" required><input data-multi-description placeholder="Description">':''}<button type="button" class="quiet-button remove-row" aria-label="Remove row">×</button>`;row.querySelector('select').addEventListener('change',event=>{const input=row.querySelector(`[data-multi-new="${kind}"]`);input.classList.toggle('hidden',event.target.value!=='__new__');input.required=event.target.value==='__new__'});row.querySelector('.remove-row').addEventListener('click',()=>row.remove());target.appendChild(row)}
function renderEntryForm(){const html=fields.map(([field,type])=>{if(type==='file')return `<label class="entry-field">${field}<input name="${field}" type="file" accept="image/png,image/jpeg"></label>`;if(type==='select')return `<label class="entry-field">${field} *<select name="${field}" required><option value="">Select ${field}</option>${options(field).map(value=>`<option value="${value}">${value}</option>`).join('')}<option value="__new__">+ Add new value...</option></select><input class="new-option hidden" data-for="${field}" placeholder="Enter new ${field.toLowerCase()}"></label>`;return `<label class="entry-field">${field} *<input name="${field}" type="${type==='number'?'number':'text'}" required ${type==='number'?'min="0" step="any"':''}></label>`}).join('');$('asset-fields').innerHTML=html+'<div class="multi-entry"><div class="multi-heading">Payloads, descriptions and individual weights *</div><div id="payload-rows"></div><button type="button" class="text-button" id="add-payload">＋ Add payload</button></div><div class="multi-entry"><div class="multi-heading">Guidance systems *</div><div id="guidance-rows"></div><button type="button" class="text-button" id="add-guidance">＋ Add guidance</button></div><div class="multi-entry"><div class="multi-heading">Anti-EW systems *</div><div id="anti-ew-rows"></div><button type="button" class="text-button" id="add-anti-ew">＋ Add anti-EW</button></div>';addMultiRow('payload');addMultiRow('guidance');addMultiRow('anti-ew')}
function fileData(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(!['image/png','image/jpeg'].includes(file.type)||file.size>2097152)return reject(new Error('Images must be PNG/JPEG and 2 MB or smaller.'));const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read image.'));reader.readAsDataURL(file)})}
async function saveAsset(event){event.preventDefault();const value=readForm(),payloadRows=[...document.querySelectorAll('#payload-rows .multi-row')];if(!value.Payload||!value.Guidance||!value['Anti Ew']||!payloadRows.every(row=>row.querySelector('[data-multi-weight]').value)){$('form-message').textContent='Complete all payload, guidance, and Anti-EW values. Payload description is optional.';return}value['Ser No']=nextSerial();delete value['Drone ID'];try{for(const field of ['Image Front','Image Back','Image Top','Image Bottom']){const input=$('asset-form').querySelector(`input[name="${field}"]`);value[field]=input?.files?.[0]?await fileData(input.files[0]):''}value['Cost (in Thousands)']=Number(value['Cost (in Thousands)']);const response=await fetch('/api/assets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});if(!response.ok)throw new Error((await response.json()).error);const saved=await response.json();fleetData.push(saved.record);$('form-message').textContent=`Saved ${saved.record['Drone ID']} to Sample.xlsx.`;renderOverview();renderService();renderGuidance();renderEWProfiles();renderUnits();renderFleet();$('asset-form').reset();$('generated-kuin').textContent='Generated on save';updateGeneratedId()}catch(error){$('form-message').textContent=`Save failed: ${error.message}`}}
function updateGeneratedId(){const value=readForm();value['Ser No']=nextSerial();$('generated-drone-id').textContent=['Command','Corps','Division','Brigade','Unit','Drone Name','Type'].every(field=>String(value[field]||'').trim())?makeDroneId(value):'Complete hierarchy fields'}
function switchView(view){document.querySelectorAll('.view-panel').forEach(panel=>panel.classList.add('hidden'));$(`${view}-view`).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===view));$('page-title').textContent={overview:'Fleet overview','add-asset':'Add asset',units:'Units & subunits',fleet:'Fleet register'}[view]}
renderEntryForm();renderOverview();renderBars('type-bars',countBy('Type'),fleetData.length);renderService();renderGuidance();renderEWProfiles();renderUnits();renderFleet();[['command-filter','Command'],['corps-filter','Corps'],['division-filter','Division'],['brigade-filter','Brigade']].forEach(([id,field])=>{populateFilter(id,field);$(id).addEventListener('change',()=>renderFleet($('fleet-search').value))});[['add-payload','payload'],['add-guidance','guidance'],['add-anti-ew','anti-ew']].forEach(([button,kind])=>$(button).addEventListener('click',()=>addMultiRow(kind)));$('asset-form').addEventListener('input',updateGeneratedId);$('asset-form').addEventListener('change',event=>{if(event.target.matches('select')){const input=document.querySelector(`[data-for="${event.target.name}"]`);if(input){input.classList.toggle('hidden',event.target.value!=='__new__');input.required=event.target.value==='__new__'}}updateGeneratedId()});$('asset-form').addEventListener('submit',saveAsset);$('asset-form').addEventListener('reset',()=>setTimeout(updateGeneratedId,0));document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));document.querySelectorAll('[data-view-target]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.viewTarget)));$('fleet-search').addEventListener('input',event=>renderFleet(event.target.value));